"""Initial migration

Revision ID: 22baa9fc071e
Revises: 
Create Date: 2025-06-06 09:06:31.407872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22baa9fc071e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
